### ISSUE TITLE
Paired end read support?

### ISSUE THREAD

**Issue by gavinmdouglas** [guertinlab/fqdedup#1]
Hi there,

Thanks for developing this useful tool. I'm wondering though - can fqdedup be used so that it's aware of paired end reads? Or is it intended solely for single-end reads?

Thanks,

Gavin

**Comment by mjg54** [comment]
Hi Gavin,

We recommend running fqdedup on each PE separately and pairing the resultant deduplicated files with fastq-pair (https://github.com/linsalrob/fastq-pair). There are rare cases when the experimental workflow puts a UMI on each PE and independent ligation of a specific UMI to a specific DNA sequence occurred independently on one PE and not the other, in which each both reads would be discarded. However, one can concatenate PE FASTQ reads into a single line and run fqdedup, then compare with the independent dedup and pairing to determine how rarely this happens. This will occur much more rarely than an incorrect base being called in the sequencing on true PCR amplicons and these not being removed by fqdedup, but the workflow above for PE reads (independent fqdedup and fastq-pair) will remove these false negative PCR duplicate amplicons that had an erroneous base call. 

Mike
